openapi: '3.0.0'
info:
  title: Single-cell API
  version: 1.0.0
  description: The main Node.js pipeline API.
  license:
    name: MIT
servers:
  - url: /v1
tags:
  - name: experiments
    description: Manage your experiments and experiment details.
paths:
  /health:
    get:
      tags:
        - heartbeat
      summary: Returns health of API
      operationId: checkHealth
      x-eov-operation-id: health#check
      x-eov-operation-handler: routes/health
      responses:
        '200':
          description: API is up
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    pattern: up
                  env:
                    type: string
                    enum:
                      - development
                      - test
                      - staging
                      - production
  /work:
    post:
      operationId: submitWork
      x-eov-operation-id: work#submit
      x-eov-operation-handler: routes/work
      requestBody:
        description: work to submit
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_path:
                  type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: {} 
  /work-results:
    post:
      operationId: receiveWork
      x-eov-operation-id: work#receive
      x-eov-operation-handler: routes/work
      requestBody:
        description: work results submitted
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: the results have been successfully received
          content:
            application/json:
              schema:
                type: object
  '/experiments/{experimentId}':
    get:
      tags:
        - experiments
      summary: Find experiment by ID
      description: Returns the main details of the experiment.
      operationId: getExperimentById
      x-eov-operation-id: experiment#findByID
      x-eov-operation-handler: routes/experiment
      parameters:
        - name: experimentId
          in: path
          description: ID of experiment to find.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Experiment'
        '400':
          description: Invalid ID supplied
        '404':
          description: Experiment not found
  /experiments/generate:
    post:
      tags:
        - experiments
      summary: Generates mock data into the DynamoDB database.
      operationId: generateExperimentMockData
      x-eov-operation-id: experiment#generateMock
      x-eov-operation-handler: routes/experiment
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema: {}

  '/experiments/{experimentId}/cell-sets':
    get:
      tags:
        - experiments
      summary: Get a hierarchical view of cell sets in the experiment.
      description: Returns a hirearchical view of cell sets in the experiment.
      operationId: getExperimentCellSetsById
      x-eov-operation-id: experiment#getCellSets
      x-eov-operation-handler: routes/experiment
      parameters:
        - name: experimentId
          in: path
          description: ID of experiment to find.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  cell_sets:
                    type: array
                    items:
                      $ref: '#/components/schemas/CellSets'
        '400':
          description: Invalid ID supplied
        '404':
          description: Experiment not found
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
  schemas:
    Experiment:
      type: object
      required:
        - experiment_id
        - experiment_name
      properties:
        experiment_id:
          type: string
        experiment_name:
          type: string
    ApiResponse:
      type: object
      required:
        - code
        - type
        - message
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
    CellSets:
      type: object
      required:
        - key
        - name
      properties:
        key:
          type: integer
          format: int32
        name:
          type: string
        rootNode:
          type: boolean
        children:
          type: array
          items:
            $ref: '#/components/schemas/CellSets'