stages:
    - install
    - build
    - test
    - deploy  # dummy stage to follow the template guidelines
    - review
    - dast
    - staging
    - canary
    - production
    - incremental rollout 10%
    - incremental rollout 25%
    - incremental rollout 50%
    - incremental rollout 100%
    - performance
    - cleanup
  
variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  ROLLOUT_RESOURCE_TYPE: deployment
  STAGING_ENABLED: "true"
  POSTGRES_ENABLED: "false"

test:
  stage: test
  image: node:latest
  needs: []
  script:
    - yarn install
    - yarn test
  variables:
    AWS_DEFAULT_REGION: 'eu-west-2'
  rules:
    - if: '$TEST_DISABLED'
      when: never
    - if: '$CI_COMMIT_TAG || $CI_COMMIT_BRANCH'


include:
  - template: Jobs/Build.gitlab-ci.yml
  - template: Jobs/Deploy.gitlab-ci.yml
