apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: api-can-spawn-workers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: can-manage-jobs
subjects:
- kind: ServiceAccount
  name: {{.Release.Namespace}}-service-account
  namespace: {{.Release.Namespace}}
