apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

# do not add `name` and `region` to this eksctl file. CI will fill these in automatically
metadata:

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 20
