experimentId: FILLED_IN_BY_API
workQueueName: FILLED_IN_BY_API
clusterEnv: FILLED_IN_BY_API
namespace: worker-refs-pull-11-merge
images:
  python: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-11-merge-177088d8f0079ac47eacd2fe1eeef4de27947339
  r: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-pull-11-merge-177088d8f0079ac47eacd2fe1eeef4de27947339
metadata:
  namespace: worker-refs-pull-11-merge
