experimentId: FILLED_IN_BY_API
workQueueName: FILLED_IN_BY_API
clusterEnv: FILLED_IN_BY_API
storageSize: FILLED_IN_BY_API
namespace: worker-refs-heads-master
images:
  python: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-079669526e73bc09a56e161687acae688eba4430
  r: 242905224710.dkr.ecr.eu-west-1.amazonaws.com/worker:refs-heads-master-079669526e73bc09a56e161687acae688eba4430
