replicaCount: 1

application:
  tier: backend

service:
  externalPort: 3000
  internalPort: 3000

prometheus:
  metrics: true

postgresql:
  enabled: false

readinessProbe:
  path: "/v1/health"

livenessProbe:
  path: "/v1/health"

ingress:
  tls:
    secretName: "tls-secret"
    enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "nginx"