{{ if and (eq .Values.biomageCi.repo "biomage-ltd/api") (eq .Values.biomageCi.sandboxId "cluster-ee") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: can-delete-pods
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: api-can-delete-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: can-delete-pods
subjects:
- kind: ServiceAccount
  name: deployment-runner
  namespace: {{ .Release.Namespace}}
{{ end }}