{{ if and (eq .Values.biomageCi.repo "biomage-ltd/api") (eq .Values.biomageCi.sandboxId "cluster-ee") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: can-delete-pods
  namespace: {{ .Release.Namespace }}
  labels:
    sandboxId: "{{ .Values.sandboxId }}"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: api-can-delete-pods
  namespace: {{.Release.Namespace}}
  labels:
    sandboxId: "{{ .Values.sandboxId }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: can-delete-pods
subjects:
- kind: ServiceAccount
  name: deployment-runner
  namespace: {{ .Release.Namespace}}
{{ end }}