{{- if .Values.service.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress

metadata:
  name: {{ template "appname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    sandboxId: "{{ .Values.biomageCi.sandboxId }}"

  annotations:
{{- if .Values.ingress.annotations }}
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
{{- if .Values.ingress.tls.enabled }}
    alb.ingress.kubernetes.io/actions.ssl-redirect: >-
      {"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port":
      "443", "StatusCode": "HTTP_301"}}
    alb.ingress.kubernetes.io/certificate-arn: >-
      arn:aws:acm:eu-west-1:242905224710:certificate/4bac7ec0-c4bc-4fda-ab73-d4159f9c5a29
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
{{- end }}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: {{ .Values.kubernetes.env }}
spec:
  rules:
  - host: {{ template "hostname" . }}
    http:
      &httpRule
      paths:
{{- if .Values.ingress.tls.enabled }}
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
{{- end }}
      - path: /*
        backend:
          serviceName: {{ template "appname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- if .Values.service.additionalHosts }}
{{- range $host := .Values.service.additionalHosts }}
  - host: {{ $host }}
    http:
      <<: *httpRule
{{- end -}}
{{- end -}}
{{- end -}}
