# the event export should be deployed only once per cluster, ie. as part of the default sandbox of the api repo
{{ if and (eq .Values.biomageCi.repo "biomage-ltd/api") (eq .Values.biomageCi.sandboxId "default") }}
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: monitoring
  name: event-exporter-trial
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: event-exporter-trial
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: ServiceAccount
    namespace: monitoring
    name: event-exporter-trial
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-exporter-cfg
  namespace: monitoring
data:
  config.yaml: |
    logLevel: info
    logFormat: json
    route:
      routes:
        - match:
          - kind: "Pod"
            receiver: "cleanup"
    receivers:
      - name: "cleanup"
        webhook:
          endpoint: "https://api-{{ .Values.biomageCi.sandboxId }}.scp-staging.biomage.net/v1/kubernetesEvents"
          headers:
            User-Agent: kube-event-exporter 1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-exporter-trial
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: event-exporter-trial
        version: v1
    spec:
      serviceAccountName: event-exporter-trial
      containers:
        - name: event-exporter-trial
          image: ghcr.io/opsgenie/kubernetes-event-exporter:v0.10
          imagePullPolicy: IfNotPresent
          args:
            - -conf=/data/config.yaml
          volumeMounts:
            - mountPath: /data
              name: cfg
      volumes:
        - name: cfg
          configMap:
            name: event-exporter-cfg
  selector:
    matchLabels:
      app: event-exporter-trial
      version: v1
{{ end }}
