name: Create backup of cognito users
env:
  region: 'eu-west-1'
  userPool: 'eu-west-1_eYTCV3Nl7'
jobs:
  backup-users:
    name: create backup of cognito users
    runs-on: ubuntu-20.04
    steps:
      - id: set-up-creds
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}
      - id: backup-users
        name: create backup json of cognito users
        uses: rahulpsd18/cognito-backup-restore
        run: |-
          cbr backup --region ${{env.region}} --profile default --pool ${{env.userPool}} --directory .

      - id: save-to-s3
        name: save backup json to s3
        run: |-
          current_date=$(date '+%Y-%m-%d.%H-%M-%S')
          aws s3api put-object --bucket ${current_date}/biomage-backups-production/data.json --key ./biomage-user-pool-case-insensitive-production.json