name: Create backup of cognito users
on:
  workflow_dispatch:
env:
  region: 'eu-west-1'
  userPool: 'eu-west-1_eYTCV3Nl7'
jobs:
  backup-users:
    name: create backup of cognito users
    runs-on: ubuntu-20.04
    steps:
      - id: setup-node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: install
        name: Install dependencies
        run: |-
          npm install -g cognito-backup-restore
      - id: set-up-creds
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.region }}
      - id: backup-users
        name: create backup json of cognito users
        run: |-
          cbr backup --region eu-west-1 --profile default --pool eu-west-1_eYTCV3Nl7 --directory .

      - id: save-to-s3
        name: save backup json to s3
        run: |-
          current_date=$(date '+%Y-%m-%d.%H-%M-%S')
          aws s3api put-object --bucket ${current_date}/biomage-backups-production/data.json --key ./biomage-user-pool-case-insensitive-production.json
