name: Lint CF files before merging
on:
  pull_request:
    branches:
      - master
    paths:
      - 'cf/**.yaml'
      - 'cf/**.yml'

jobs:
  get-modified-templates:
    name: Fetch paths to modified CloudFormation templates
    runs-on: ubuntu-20.04
    outputs:
      files: ${{ steps.check-number-of-cf-files.outputs.files }}
      num-files: ${{ steps.check-number-of-cf-files.outputs.num-files }}
    steps:
      - id: get-changed-files
        name: Get changed files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: check-number-of-cf-files
        name: Check CloudFormation templates
        run: |-
          # Merge all modified and renamed files into one JSON array
          #jq -s add ${HOME}/files_added.json ${HOME}/files_modified.json ${HOME}/files_renamed.json > ${HOME}/files_to_check.json

          cat ${HOME}/files.json
          echo

          # Select those that are CF templates (path starts with `cf/`)
          jq '[.[] | select(match("^cf/"))]' ${HOME}/files.json > ${HOME}/cf_files.json

          # Set as output the minified JSON.
          echo "::set-output name=files::$(jq -c . < ${HOME}/cf_files.json)"
          echo "$(jq -c . < ${HOME}/cf_files.json)"
          echo "::set-output name=num-files::$(jq '. | length' ${HOME}/cf_files.json)"

  lint-templates:
    name: Lint changed CloudFormation template
    runs-on: ubuntu-20.04
    needs: get-modified-templates
    if: needs.get-modified-templates.outputs.num-files > 0
    steps:
      - id: checkout
        name: Check out source code
        uses: actions/checkout@v2

      - id: lint
        name: Lint template
        uses: scottbrenner/cfn-lint-action@1.6.1
        with:
          args: ${{fromJson(needs.get-modified-templates.outputs.files)}}